### ISSUE TITLE
Support the nousernameinx flag

### ISSUE THREAD

**Issue by jkcoxson** [RustCrypto/PAKEs#109]
Hello, I'm writing a client implementation of SRP, but the server I'm connecting to requires that the nousernameinx flag be set. How would I go about doing this, or what would this library have to change to support this?
Thanks!

**Comment by tarcieri** [comment]
I've never heard of the "nousernameinx" flag. Do you know of a specification for it?

**Comment by tarcieri** [comment]
Was there a workaround for this?
