### ISSUE TITLE
SRP: tools::powm should use faster constant time exponentiation

### ISSUE THREAD

**Issue by jpgoldberg** [RustCrypto/PAKEs#18]
There are methods for much more efficient and cryptographically appropriate modular exponentiation than what is currently implemented.

I'm not familiar enough with the Rust ecosystem to specifically recommend something at this point. (Indeed, I read this code in the hopes of finding the recommended practice.)

**Comment by newpavlov** [comment]
Can you link any references, which we can use? `srp` crate is explicitly not constant-time (see README, I probably also should add disclaimer to the crate docs), but I will be happy to accept any PRs which will improve crates in this regard!

**Comment by jbis9051** [comment]
This was fixed by https://github.com/RustCrypto/PAKEs/pull/78 and should be closed

**Comment by tarcieri** [comment]
Fixed in #79
