### ISSUE TITLE
Why is powm used instead of the built in modpow method in BigInt?

### ISSUE THREAD

**Issue by jbis9051** [RustCrypto/PAKEs#77]
Why is https://github.com/RustCrypto/PAKEs/blob/master/srp/src/tools.rs#L3 used instead of https://docs.rs/num-bigint/latest/num_bigint/struct.BigUint.html#method.modpow?

**Comment by tarcieri** [comment]
Much of the code in this repo was contributed early and has not seen regular updates.

I agree the built-in modpow should be used.
